# Generated by Django 5.2 on 2025-04-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('pid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('sizes_listed', models.TextField()),
                ('img_url', models.URLField(max_length=500)),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Shirt',
                'verbose_name_plural': 'Shirts',
                'db_table': 'shirts',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=10)),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.shirt')),
            ],
            options={
                'unique_together': {('shirt', 'size_name')},
            },
        ),
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shoulder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sleeve_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('size', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='products.size')),
            ],
        ),
    ]
